# Generated by Django 5.2.1 on 2025-07-14 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255, verbose_name='نام کامل')),
                ('legalId', models.CharField(max_length=50, verbose_name='شناسه قانونی')),
                ('phoneNumber', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'پروفایل سرمایه\u200cگذار',
                'verbose_name_plural': 'پروفایل\u200cهای سرمایه\u200cگذار',
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingPermit', models.CharField(blank=True, max_length=500, null=True, verbose_name='مجوز ساختمان')),
                ('draftSeparation', models.CharField(blank=True, max_length=500, null=True, verbose_name='طرح تفکیک')),
                ('municipalityInquiry', models.CharField(blank=True, max_length=500, null=True, verbose_name='استعلام شهرداری')),
                ('environmentalPermit', models.CharField(blank=True, max_length=500, null=True, verbose_name='مجوز محیط زیست')),
                ('firePermit', models.CharField(blank=True, max_length=500, null=True, verbose_name='مجوز آتش\u200cنشانی')),
                ('engineeringSystemPermit', models.CharField(blank=True, max_length=500, null=True, verbose_name='مجوز سیستم مهندسی')),
            ],
            options={
                'verbose_name': 'مدارک قانونی',
                'verbose_name_plural': 'مدارک قانونی',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255, verbose_name='نام کامل')),
                ('nationalCode', models.CharField(max_length=20, unique=True, verbose_name='کد ملی')),
                ('birthDate', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('photo', models.CharField(blank=True, max_length=500, null=True, verbose_name='عکس')),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('position', models.CharField(max_length=100, verbose_name='سمت')),
                ('role', models.CharField(choices=[('admin', 'مدیر'), ('manager', 'سرپرست'), ('employee', 'کارمند')], default='employee', max_length=20, verbose_name='نقش')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='بخش')),
                ('employmentType', models.CharField(choices=[('fullTime', 'تمام وقت'), ('partTime', 'نیمه وقت'), ('contractor', 'پیمانکار'), ('consultant', 'مشاور')], max_length=20, verbose_name='نوع استخدام')),
                ('startDate', models.DateField(verbose_name='تاریخ شروع')),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام کاربری')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='رمز عبور')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee', verbose_name='سرپرست')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('relation', models.CharField(max_length=100, verbose_name='نسبت')),
                ('phoneNumber', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergencyContact', to='api.employee', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس اضطراری',
                'verbose_name_plural': 'اطلاعات تماس اضطراری',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalIdCard', models.CharField(blank=True, max_length=500, null=True, verbose_name='کارت ملی')),
                ('resume', models.CharField(blank=True, max_length=500, null=True, verbose_name='رزومه')),
                ('insuranceRecord', models.CharField(blank=True, max_length=500, null=True, verbose_name='سابقه بیمه')),
                ('degreeCertificate', models.CharField(blank=True, max_length=500, null=True, verbose_name='مدرک تحصیلی')),
                ('workLicense', models.CharField(blank=True, max_length=500, null=True, verbose_name='مجوز کار')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.employee', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'مدارک کارمند',
                'verbose_name_plural': 'مدارک کارمندان',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان پروژه')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('category', models.CharField(max_length=100, verbose_name='دسته\u200cبندی')),
                ('ownershipStatus', models.CharField(max_length=100, verbose_name='وضعیت مالکیت')),
                ('landArea', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مساحت زمین')),
                ('infrastructure', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='زیرساخت')),
                ('numFloors', models.IntegerField(verbose_name='تعداد طبقات')),
                ('usageEachFloor', models.TextField(verbose_name='کاربری هر طبقه')),
                ('structuralSkeleton', models.CharField(max_length=100, verbose_name='اسکلت سازه')),
                ('hvacSystems', models.CharField(max_length=100, verbose_name='سیستم\u200cهای تهویه')),
                ('foundationTypes', models.CharField(max_length=100, verbose_name='نوع فونداسیون')),
                ('wallSystems', models.CharField(max_length=100, verbose_name='سیستم دیوارها')),
                ('insulationSystems', models.CharField(max_length=100, verbose_name='سیستم عایق\u200cبندی')),
                ('roofTypes', models.CharField(max_length=100, verbose_name='نوع سقف')),
                ('mepSystems', models.CharField(max_length=100, verbose_name='سیستم\u200cهای MEP')),
                ('smartSystems', models.CharField(max_length=100, verbose_name='سیستم\u200cهای هوشمند')),
                ('projectStatus', models.IntegerField(choices=[(1, 'فعال'), (2, 'در حال پیشرفت'), (3, 'غیرفعال')], default=3, verbose_name='وضعیت پروژه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('startDate', models.DateField(verbose_name='تاریخ شروع')),
                ('image', models.CharField(blank=True, max_length=500, null=True, verbose_name='تصویر پروژه')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('investorProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.investorprofile', verbose_name='پروفایل سرمایه\u200cگذار')),
                ('legalInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.legaldocument', verbose_name='اطلاعات قانونی')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.project', verbose_name='پروژه'),
        ),
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='employees', to='api.project', verbose_name='پروژه\u200cها'),
        ),
    ]
