# Generated by Django 5.2.1 on 2025-07-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile',
        ),
        migrations.AddField(
            model_name='customuser',
            name='companyName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شرکت'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fullName',
            field=models.CharField(default='No Name', max_length=255, verbose_name='نام کامل'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر'), ('employee', 'کارمند')], default='employee', max_length=20, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر'), ('employee', 'کارمند')], default='employee', max_length=20, verbose_name='نقش'),
        ),
    ]
